### ISSUE TITLE
Keine Daten seit einem Runtastic Update

### ISSUE THREAD

**Issue by danielpapenfuss** [timoschlueter/php-runtastic#10]
Hey,

ich bekomm seit Runtastic die Webseite überarbeitet hat keine Daten mit der Klasse mehr. Ist das jemand anderem auch schon aufgefallen?

Wenn ich Zeit finde werde ich auch die Tage mal schauen ob ich die Ursache ein wenig eingrenzen kann.

Gruß,
Daniel

**Comment by mipapo** [comment]
@danielpapenfuss Schau doch mal hier: https://github.com/timoschlueter/php-runtastic/issues/8 Dort wurde das Thema schon bearbeitet und schon erledigt. Wenn du dir die aktuellste Version ziehst, soll es angeblich gehen

**Comment by timoschlueter** [comment]
Sollte in 7e3d83e7444c71ef5af92a57cfd3e6630d45db95 behoben sein.
Das Problem ist hier nicht die Veränderte Runtastic-Website, sondern scheinbar ein Rate-Limit, was seit kurzem im Backend aktiv ist. Ich kann lediglich die letzten 420 Aktivitäten vom Backend herunterladen. Sobald ich versuche, 421 Aktivitäten zu ziehen, liefert die API keine Ergebnisse mehr.

Ich habe im commit 7e3d83e7444c71ef5af92a57cfd3e6630d45db95 einen Workarround eingebaut, indem ich erst das Array der Aktivitäten-IDs absteigend sortiere und anschließend auf 420 Aktivitäten beschneide. Keine schöne Lösung, aber sollte erst einmal funktionieren.

Man könnte jetzt versuchen, eine Art "Paging"-Funktion einzubauen. Das heißt, mehrere Calls zum Backend von Runtastic, bis man alle Aktivitäten gefunden hat. Schaue ich mir vielleicht am Wochenende mal an, wenn ich nicht durch die Osterfeiertage im "Fresskoma" liege ;)
