### ISSUE TITLE
Composer

### ISSUE THREAD

**Issue by sergeyvolkov** [timoschlueter/php-runtastic#7]
Please add your package to the Composer repository
Composer https://getcomposer.org/
Packagist https://packagist.org/

**Comment by mnlg** [comment]
+1

**Comment by yoannyviquel** [comment]
+1
It would be really great to have it by composer

**Comment by timoschlueter** [comment]
I never used composer before. Does anyone of you have a quick start guide or something like that where i can get an overview over the way it works?

**Comment by timoschlueter** [comment]
I will look into it this weekend. Maybe i have it on composer as soon as monday. :)

**Comment by timoschlueter** [comment]
I added the package to packagist. Can someone please check if its working? :)

https://packagist.org/packages/timoschlueter/php-runtastic

**Comment by mnlg** [comment]
Doing a `composer require timoschlueter/php-runtastic master-dev` seems to work for me.

**Comment by timoschlueter** [comment]
Thanks @mnlg. I will close this issue then.

**Comment by mnlg** [comment]
Sorry, i've just checked again and the autoloader doesn't seem to work at all.

**Comment by timoschlueter** [comment]
Since i dont use composer: What seems to be the problem? The composer.json has been commited by @ferranmarlet. Maybe he can help? :)

**Comment by ferranmarlet** [comment]
My fault. It was necessary to add an autoload directive to the composer.json.
I have done it, and I have tested it on my own packagist account. It seems to work, and I have sent you another pull request now.

**Comment by timoschlueter** [comment]
I merged the pull request. Should work now. I also linked this github repository to packagist. 
Composer should therefore work now.

**Comment by ferranmarlet** [comment]
It works. Thank you Timo.

**Comment by timoschlueter** [comment]
Great! Thank you @ferranmarlet for the fix. :)
