### ISSUE TITLE
Class stopped working

### ISSUE THREAD

**Issue by nordmograph** [timoschlueter/php-runtastic#8]
Hello,

It seems there are some changes in the API and the class is currently broken

Notice: Undefined offset: 1 in class.runtastic.php on line 118
Notice: Undefined offset: 1 in class.runtastic.php on line 200
Warning: Invalid argument supplied for foreach() in class.runtastic.php on line 209
Warning: Invalid argument supplied for foreach() in class.runtastic.php on line 288

**Comment by timoschlueter** [comment]
Runtastic changed the layout of their Website. The class uses DOM parsing to retrieve the authenticity_token. Since the DOM changed, thats no longer possible.

Unfortunately, i cant look into the problem before monday :/
